export const LOGIN_FETCH_REQUEST = "LOGIN_FETCH_REQUEST";
export const LOGIN_FETCH_SUCCESS = "LOGIN_FETCH_SUCCESS";
export const LOGIN_FETCH_FAIL = "LOGIN_FETCH_FAIL";

export const USERDETAILS_FETCH_REQUEST = "USERDETALS_FETCH_REQUEST";
export const USERDETAILS_FETCH_SUCCESS = "USERDETALS_FETCH_SUCCESS";
export const USERDETAILS_FETCH_FAIL = "USERDETALS_FETCH_FAILE";
